# Generated by Django 6.0.3 on 2026-05-02 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2100),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["artist", "release_year"], name="album_artist_year_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["genre", "release_year"], name="album_genre_year_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["title"], name="album_title_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="review_rating_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["album", "rating"], name="review_album_rating_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["listened_on"], name="review_listened_on_idx"),
        ),
    ]
